name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y zip

      - name: Set Version
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Install latest sysuthesis
        run: l3build install

      - name: Generate logos
        working-directory: test
        run: |
          cat << 'EOF' > sysu-emblem.tex
          \documentclass[tikz]{standalone} \usepackage{sysuvisual}
          \begin{document} \sysudraw{badge} \end{document}
          EOF
          cat << 'EOF' > sysu-name-cn.tex
          \documentclass[tikz]{standalone} \usepackage{sysuvisual}
          \begin{document} \sysudraw{name-cn}[landscape][2.5cm][white][draw=sysugreen, line width=1pt] \end{document}
          EOF
          latexmk -pdf -halt-on-error sysu-*.tex

      - name: Zip CTAN package
        run: |
          l3build ctan
          mv sysuthesis-ctan.zip sysuthesis-ctan-$VERSION.zip

      - name: Zip USER package
        run: |
          mv build/unpacked/sysu* .
          mv test/* .
          zip -r sysuthesis-user-$VERSION.zip sysuthesis-sample* *.cls *.sty *.pdf LICENSE README.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sysuthesis-*.zip
          generate_release_notes: true